### ISSUE TITLE
Questions (Important and urgent)

### ISSUE THREAD

**Issue by Ashtor** [DavidTimms/ChatSafe#3]
Hi
I read that the chat is safe,so I just wonder few things and here they are:
1. How safe is the chatsafe?
2. Is the chat logged somewhere on the server? and if so.. Where and for how long?
3. Does the chat/messages in a room gets cleared after awhile? and if so.. when? because the messages doesn't get cleared automatically after a certain time wich should be or the messages should be cleared when all leave the room. Please consider to make the messages disappear after awhile or after everyone leaves the room

Here's my suggestions:
1. All messages that the user post in a room,gets cleared once the user leaves and rejoin (messages doesn't get stored at all anywhere).. same goes for the room gets cleared once everyone leaves .please make that.

**Comment by DavidTimms** [comment]
Hi Ashtor, thanks for checking out the project. I only created it to get experience with the technologies and I am by no means a security expert, so if you are looking for secure private messaging, there are much more robust alternatives available.

If you are looking to adapt the code into your own project or learn from it, then it may be useful to you.

To address you questions, messages are stored in memory on the server as long as the conversation exists. Once the last chatter disconnects, the messages are garbage collected, and there should be no trace of the conversation on the server. Even during the conversation, while the messages are stored temporarily on the server, they are encrypted, so the key in the URL hash is required to read them. The hash key is not sent to the server, so if the server is compromised, an attacker should not be able to read the messages.
